### ISSUE TITLE
Update stable version in repo from 0.2.0 to 0.2.2-beta.0

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.knmi-weather#33]
# Think about update stable version to 0.2.2-beta.0
**Version**: stable=**0.2.0** (179 days old) => latest=**0.2.2-beta.0** (15 days old)
**Installs**: stable=**53** (66.25%), latest=**19** (23.75%), total=**80**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L637)

**Comment by DutchmanNL** [comment]
https://github.com/ioBroker/ioBroker.repositories/pull/922
https://github.com/iobroker-community-adapters/ioBroker.knmi-weather/commit/7a88040a33bb0930726483e8a23e193ccd7f6764
